# Generated by Django 5.0.3 on 2025-06-04 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('orderID', models.AutoField(primary_key=True, serialize=False)),
                ('orderAmount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('orderShipAddress', models.CharField(max_length=255)),
                ('orderPhone', models.CharField(max_length=20)),
                ('orderDate', models.DateTimeField(auto_now_add=True)),
                ('orderShipped', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('productID', models.AutoField(primary_key=True, serialize=False)),
                ('productName', models.CharField(max_length=100)),
                ('productPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('productDesc', models.TextField()),
                ('productStock', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('categoryID', models.AutoField(primary_key=True, serialize=False)),
                ('categoryName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('roleID', models.AutoField(primary_key=True, serialize=False)),
                ('roleName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('detailID', models.AutoField(primary_key=True, serialize=False)),
                ('detailName', models.CharField(max_length=100)),
                ('detailPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('detailQuantity', models.PositiveIntegerField()),
                ('detailOrderID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.order')),
                ('detailProductID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='productCategoryID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.productcategory'),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userID', models.AutoField(primary_key=True, serialize=False)),
                ('userEmail', models.EmailField(max_length=254, unique=True)),
                ('userPassword', models.CharField(max_length=128)),
                ('userFirstName', models.CharField(max_length=50)),
                ('userLastName', models.CharField(max_length=50)),
                ('userPhone', models.CharField(max_length=20)),
                ('userAddress', models.CharField(max_length=255)),
                ('userRoleID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.role')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='orderUserID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.user'),
        ),
    ]
